[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = partitions.csv
extra_scripts = pre:scripts/embed_web.py
monitor_speed = 115200
test_build_src = true
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    adafruit/Adafruit NeoPixel@^1.12.0
